### ISSUE TITLE
Building the kernel

### ISSUE THREAD

**Issue by gvlfm78** [dpuyosa/android_kernel_wiko_l5460#1]
Hey there! I just found this repository and realised there was someone else working on a Wiko Fever custom kernel. I have my own repository of it [here](https://github.com/gvlfm78/android_kernel_wiko_l5460). I have, though, been having a problem in the building of the kernel, which seems to occur in the original source from Wiko too. It might be me not building it correctly, but here is the error:

`[gvlfm78@Lenovo android_kernel_wiko_l5460]$ make ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- -j8`
`scripts/kconfig/conf --silentoldconfig Kconfig`
`  CHK     include/config/kernel.release`
`make[1]: Nothing to be done for 'dct/DrvGen'.`
`  CHK     include/generated/uapi/linux/version.h`
`./tools/dct/DrvGen ./drivers/misc/mediatek/mach/mt6735/l5460/dct/dct/codegen.dws arch/arm64/boot/dts/ arch/arm64/boot/dts/ cust_dtsi`
`make: execvp: ./tools/dct/DrvGen: Permission denied`
`make: *** [scripts/drvgen/drvgen.mk:32: arch/arm64/boot/dts/cust.dtsi] Error 127`
`make: *** Waiting for unfinished jobs....`
`[gvlfm78@Lenovo android_kernel_wiko_l5460]$`

My question is, have you been able to build either the original kernel or your modified version? If so, how?

Thank you for your time,
gvlfm78

**Comment by dpuyosa** [comment]
Hello,
I use the commands in the [buildKernel](https://github.com/dpuyosa/android_kernel_wiko_l5460/blob/master/buildKernel) file.
```
make mrproper
export ARCH=arm64
make O=out TARGET_ARCH=arm64 l5460_defconfig
make O=out TARGET_ARCH=arm64 menuconfig
make O=out TARGET_ARCH=arm64 -j30
```
My repo is the original Kernel from [Wiko Geek](http://www.wikogeek.com/index.php?telephone=FEVER+&region=EUROPE&version=ANDROID+MARSHMALLOW), I added interactiveX governor and played around with the Kernel config.

Btw, I was just able to build the Kernel from the downloaded sources and it worked without problems.

Your problem seems to be about system permissions. Try to run as root or place the needed tools into an accessible directory for the user *gvlfm78*

**Comment by gvlfm78** [comment]
I did notice it was a permissions problem, running the command as root did not change anything. The toolchain is in a folder right next to the kernel source.

I'm going to try compiling the original source first to see if it's got anything to do with my modifications to it.

Thank you for reading.

**Comment by dpuyosa** [comment]
Keep me posted 💪

**Comment by gvlfm78** [comment]
Ok.. So compiling the original source works, and also the commit where I added the first few CPU governors. Adding the other governors without the IO Schedulers causes a different error, so I'm going to revert and try adding only one to see what is causing the error.

**Comment by gvlfm78** [comment]
Alright... So basically one of the features I included in one of the first commits caused the whole thing to become unusable, which means I have to start all over again from scratch. At this point I ask you what you were planning on doing with your version of the kernel (self-usage, publishing anywhere?) and if you don't mind joining forces to avoid duplication of effort (for example me adding bits I had already added over on my version like the extra I/O Schedulers and some multicore-focused CPU governors)

**Comment by dpuyosa** [comment]
I did it only for fun and to learn how to do it, and since I was unable to find another repo at the time, I created it.
I am buying a new phone soon, since this one is starting to decompose, so I don't think that I will be doing any more changes to the Kernel.

**Comment by gvlfm78** [comment]
Alright then. I'll continue working on my own from your source.

**Comment by gvlfm78** [comment]
@dpuyosa I just have one question, did you ever compile and use the kernel? Because I just managed to compile it but it's 14MB instead of the stock 6MB, which means the resulting boot.img is too big. Did you also incur in this problem?

**Comment by dpuyosa** [comment]
Yes, I am currently using the kernel compiled from my repo.

In the kernel output directory there must be these files. The one that I
use is "Image.gz-dtb".


​

1.- Then, with Carliv Image Kitchen
<https://gitlab.com/carliv/carliv_image_kitchen> I unpack the original
"boot.img" downloaded from Wiko.
2.- In the unpack output, replace "boot.img-kernel" with "Image.gz-dtb"
(keep "boot.img-kernel" as the filename).
3.- Repack.
4.- Flash the new "boot,img" to the phone.

For flashing I use the *SP Flash Tool*. Read carefully how to setup and use
it, so you don't brick the device.
Use *MTK_AllInOne_DA.bin *and *MT6753_Android_scatter.txt* from Wiko, and
only tick the "boot" file (clicking in the path you can select the file).


​
I hope that this may help you.


2017-11-03 22:02 GMT+01:00 gvlfm78 <notifications@github.com>:

**Comment by dpuyosa** [comment]
@gvlfm78 
Yes, I am currently using the kernel compiled from my repo. 
In the kernel output directory there must be these files. The one that I use is "Image.gz-dtb".
![kerneloutput](https://user-images.githubusercontent.com/8700324/32408483-cf3262c6-c198-11e7-80ae-6a6960b925d3.png)

1. Then, with [Carliv Image Kitchen](https://gitlab.com/carliv/carliv_image_kitchen) I unpack the original "boot.img" downloaded from Wiko.
2. In the unpack output, replace "boot.img-kernel" with "Image.gz-dtb" (keep "boot.img-kernel" as the filename).
3. Repack.
4. Flash the new "boot,img" to the phone.

For flashing I use the **SP Flash Tool**. Read carefully how to setup and use it, so you don't brick the device.
Use **MTK_AllInOne_DA.bin** and **MT6753_Android_scatter.txt** from Wiko, and only tick the "boot" file (clicking in the path you can select the file).
![sttools](https://user-images.githubusercontent.com/8700324/32408503-17d15118-c199-11e7-86cb-77cdc6527365.png)


I hope that this may help you.

**Comment by gvlfm78** [comment]
Alright, so I managed to flash the kernel with the boot.img, I found out I was using the Image file instead of the compressed one, but now it just keeps showing the boot image over and over. I guess that's a problem with the stuff I've added and not one with the flashing method.

**Comment by gvlfm78** [comment]
Yes indeed by setting interactiveplus as the default governor it boots, and when I try to enable pegasusq or wheatley with kernel Adiutor the phone reboots... This means there's something wrong with my implementation of the two new governors, but I have no idea how to find out _what_  is wrong

**Comment by dpuyosa** [comment]
@gvlfm78 
The rotation thing was that I had the gyro driver disabled in the defconfig for some reason.

**Comment by gvlfm78** [comment]
Does that mean it was already disabled with the config they provided from source?
Also, how did you know which gyro driver to enable? I see you enabled MPU6050G but if I recall correctly there were more available.

Thank you again for answering,
gvlfm78

P.S.: I've managed to fix the governors I'd added so that is no longer a problem
